### ISSUE TITLE
fix: ganache simulation fails with out of gas

### ISSUE THREAD

**Issue by mds1** [mds1/convex-shutdown-simulation#7]
Discovered by @feuGeneA in https://github.com/mds1/convex-shutdown-simulation/pull/4, moving tracking of that issue here. 

Ganache simulation fails with out of gas error, which @gnidan and @davidmurdoch are planning to look into. For reference, here's how much gas used is reported when simulating this transaction with various tools:

Gas usage at block 13,724,056:

- Foundry: 15,515,282 (using the fix in https://github.com/gakonst/foundry/pull/524)
- Hardhat: 15,344,483
- Dapptools: 16,779,553 (I don't think this accounts for refunds)
- Tenderly: 15,537,677 (not in this repo, but will check it manually using their simulator)

**Comment by mds1** [comment]
description updated with gas usage

**Comment by mds1** [comment]
Note that the foundry one isn't entirely accurate as that's accounting for other gas usage in `testShutdownCost()` when we get the owner, etc. So that needs to be updated

**Comment by brockelmore** [comment]
1 point here that likely make up the difference between foundry and tenderly: we remove the base tx cost + calldata cost, i cant imagine tenderly does. This likely accounts for roughly 21064 of our difference wrt tenderly

**Comment by nebojsa94** [comment]
Hey @brockelmore, curious why you remove base + calldata cost, what do you achieve with that?

**Comment by brockelmore** [comment]
we remove the base cost because it's just noise especially when trying to gas optimize, for example, what may normally be an internal function, but during gas testing they are testing it explicitly. We remove calldata for a similar reason, but slightly different. since we test with smart contracts, we always have an extra 64 gas that doesn't change regardless of what you do internally. so the long and short of it is, we want to report execution cost of tests as pure as possible and let people not have to do redundant math in their head
